language: python
sudo: required
dist: trusty

python:
  - "3.5"
install:
  # python
  - pip3 install PyQt5
  - pip3 install -r ./requirements-dev.txt
script:
 #- flake8
 - "python -m pytest \
    -v \
    -m 'not non_travis' \
    --cov=version"
after_success:
  - bash <(curl -s https://codecov.io/bash)
