language: python
sudo: required
dist: trusty

python:
  - "3.5"
install:
  # python
  - pip3 install PyQt5
  - pip3 install -r ./requirements-dev.txt
script:
 - python -m pytest -vv --flake8 -m 'not non_travis' --cov=happypanda .
after_success:
  - bash <(curl -s https://codecov.io/bash)
